### ISSUE TITLE
group-based assessment of the quality

### ISSUE THREAD

**Issue by hdemarco4** [rooftopsparrow/resource-locking#27]
"Use this assignment's Online text to provide the full names of the participants who collaborated on the development of the product. Online text must also include a group-based assessment of the quality of the submitted program."

**Comment by rooftopsparrow** [comment]
Thanks for tracking this @hdemarco4.

Full Name: Jonathan Nicholson
I think the the quality of the software is supported with quality metrics: standard java comments, unit tests, and code coverage, and continuous integration. The algorithm is probably too simple for every device, but we're not trying to do every device. I think we're submitting a quality deliverable that meets expectations of the "client". I think there could be more tests and I think there could be more parameter checking on the device itself ( if we do not get that in before submission ).

**Comment by Mojac** [comment]
Full name: Michael Palme

**Comment by arcturas1** [comment]
Full Name: Jonathan Grant
I believe that our code is of high correctness and good quality; it should definitely meet specifications. Given our constraints of essentially never having time to work together as a full group, I think that our product is remarkably solid. I also agree that the algorithm does not satisfy the general case, but since it does not need to, this is well and good. 

I do agree that the code quality could be improved by refactoring it to be more defensive, however developing tests and defenses for this given our intra-group time constraints would require significantly more time, so reserving such changes for a future release is a good idea in my mind.

**Comment by hdemarco4** [comment]
Full name: Heather DeMarco

**Comment by rooftopsparrow** [comment]
> We believe the project is of high correctness and good quality, and is supported with quality metrics: standard javadoc comments, unit tests, high code coverage, and a continuous integration pipeline. We believe the algorithm is correct and fulfills the expectectation of the specification for the specific use case and we have a solid deliverable.

**Comment by rooftopsparrow** [comment]
Confirmed in Slack this is the comment we will use.
